version: '3.8'

services:
  #Postgres database
  postgres:
    image: postgres
    restart: always
    container_name: smena_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: testpassword

  # Redis service
  redis:
    image: redis
    restart: always
    container_name: smena_redis
    ports:
      - 6379:6379

  # Wkhtmltopdf service
  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    restart: always
    ports:
      - 8088:80
